// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mozzzkxlmhwmniloafzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1venp6a3hsbWh3bW5pbG9hZnpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMjk2NDUsImV4cCI6MjA2NTgwNTY0NX0.RmOZNQgKD-126CwFi8-My8iTw13YzMNMIX1zWZ26vgY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);